### ISSUE TITLE
Motion detection by camera/frigate

### ISSUE THREAD

**Issue by TawfikDaim** [TawfikDaim/home_automation#89]

**Comment by TawfikDaim** [comment]
This automation is currently under testing to see if motion triggers will work.
Ideally when a motion is detected it should send a whatsapp message.

```
alias: motion detected at main door by camera/frigate
description: ""
triggers:
  - trigger: state
    entity_id:
      - switch.maindoor_motion
    to: "on"
conditions: []
actions:
  - data:
      message: Motion detected at main door
      target: 120363318337012938@g.us
    action: notify.greenapi
mode: single

```
