### ISSUE TITLE
Notification by whatsapp

### ISSUE THREAD

**Issue by TawfikDaim** [TawfikDaim/home_automation#90]
Dependency: home assistant needs to be accesible from outside to be able to attach the image, here the location of the image must be inside www folder and will eb accessed as 'http://your-home-assistant-url/local/motion_3.jpg'

Follow steps below...(https://github.com/t0mer/green-api-custom-notifier)

login to https://console.green-api.com
get you API key from greenapi project
configure whatsapp number 
The free account is limited to 3 chats (Group or Private).
go to API/ServiceMethods/GetContacts to get list of contacts and groups (mark the id of the target group to send notifications to)
	{
		"id": "120363345070380596@g.us",
		"name": "Notifications ",
		"type": "group"
	},
Download the [green-api-custom-notifier](https://github.com/t0mer/green-api-custom-notifier), place it under the custom_components folder. Restart Home Assistant and add the following section to your configuration.yaml file:
notify:
  - platform: greenapi
    name: greenapi
    instance_id:  #REQUIRED: Set the instanceid (from greenapi)
    token:  #REQUIRED: Set the greenapi token.  (from greenapi)
    target:  #OPTIONAL! Set the detault target. If you set the default target here, you won't have to specify it again in your service calls.
use the following code inside home assistant automation to send a message 
```
alias: Send WhatsApp Message
trigger:
  - platform: state
    entity_id: binary_sensor.maindoor_motion
    to: 'on'
action:
  - service: notify.greenapi
      data:
        target: 201201971120-1630483083@g.us
        message: Motion detected at main door
        data:
          file: /config/www/motion_3.jpg
      action: notify.greenapi
mode: single
```

**Comment by TawfikDaim** [comment]
to make sure pictures are dymanically stored by frigate camera

add this to frigate.yaml

```
  maindoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Newipad1@192.168.1.103:554/Steaming/Channels/101
          roles:
            - rtmp
            - detect
    motion:
      mask:
        - 2373,0,1928,627,0,573,0,0
    **snaphots:
      enabled: true
      timestamp: true
      path: "/config/www/snaphots"**


```

add this to docker-compose file
